apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-connect-exporter
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-connect-exporter
rules:
- apiGroups: [""]
  resources: ["pods", "nodes"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-connect-exporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pod-connect-exporter
subjects:
- kind: ServiceAccount
  name: pod-connect-exporter
  namespace: monitoring
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: pod-connect-exporter
  namespace: monitoring
  labels:
    app: pod-connect-exporter
spec:
  selector:
    matchLabels:
      app: pod-connect-exporter
  template:
    metadata:
      labels:
        app: pod-connect-exporter
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "28880"
    spec:
      serviceAccountName: pod-connect-exporter
      hostPID: true
      containers:
      - name: exporter
        image: your-registry/pod-connect-exporter:latest
        imagePullPolicy: Always
        securityContext:
          privileged: true
          runAsUser: 0
        ports:
        - containerPort: 28880
          name: metrics
          protocol: TCP
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: proc
          mountPath: /host/proc
          readOnly: true
        - name: containerd-sock
          mountPath: /run/containerd/containerd.sock
        env:
        - name: PROC_PATH
          value: /host/proc
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        livenessProbe:
          httpGet:
            path: /healthz
            port: metrics
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /healthz
            port: metrics
          initialDelaySeconds: 5
          timeoutSeconds: 5
      volumes:
      - name: proc
        hostPath:
          path: /proc
      - name: containerd-sock
        hostPath:
          path: /run/containerd/containerd.sock
---
apiVersion: v1
kind: Service
metadata:
  name: pod-connect-exporter
  namespace: monitoring
  labels:
    app: pod-connect-exporter
spec:
  type: ClusterIP
  ports:
  - port: 28880
    targetPort: metrics
    protocol: TCP
    name: metrics
  selector:
    app: pod-connect-exporter 